apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongo
      image: mongo:7.0.5-jammy
      imagePullPolicy: IfNotPresent
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secretdb
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretdb
              key: password
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: simple-folder

  volumes:
    - name: simple-folder
      hostPath:
#        path: "F:\\backup\\projects\\otus_msa\\volumes"
        path: /volumes
        type: DirectoryOrCreate

  restartPolicy: Always
  