apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
    dz: {{ .Values.label }}
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: store
spec:
  selector:
    app: store
    dz: {{ .Values.label }}
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: delivery
spec:
  selector:
    app: delivery
    dz: {{ .Values.label }}
  ports:
    - port: 8004
      protocol: TCP
      targetPort: 8004
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: pay
spec:
  selector:
    app: pay
    dz: {{ .Values.label }}
  ports:
    - port: 8003
      protocol: TCP
      targetPort: 8003
  type: ClusterIP