apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter
  labels:
    app: mongo-exporter
    dz: {{ .Values.label }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exporter
      dz: {{ .Values.label }}
  template:
    metadata:
      name: mongo-exporter
      labels:
        app: mongo-exporter
        dz: {{ .Values.label }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: '/metrics'
        prometheus.io/port: "9216"
    spec:
      containers:
        - name: mongo-exporter
          image: percona/mongodb_exporter:0.20
          imagePullPolicy: Always
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretdb
                  key: password
            - name: mongo_endpoint
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongo_endpoint

          command: ["/mongodb_exporter", "--mongodb.uri=mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(mongo_endpoint):27017/?authMechanism=SCRAM-SHA-1", "--mongodb.indexstats-colls=Users.Users", "--mongodb.collstats-colls=Users.Users"]
      restartPolicy: Always

