apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    dz: {{ .Values.label }}
spec:
  rules:

      - host: cadvisor
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cadvisor
                  port:
                    number: 8080
      - host: grafana
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: grafana
                  port:
                    number: 3000
      - host: prometheus-server
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: prometheus-server
                  port:
                    number: 9090
    #- host: arch.homework
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: webapp
                  port:
                    number: 8000
{{/*    - host: prometheus*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: webapp*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}
{{/*    - host: grafana*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: webapp*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}