apiVersion: v1
kind: Service
metadata:
  name: mongo-exporter

spec:
  selector:
    app: mongo-exporter
    dz: {{ .Values.label }}
  ports:
    - port: 9216
      protocol: TCP
      targetPort: 9216
  type: LoadBalancer