apiVersion: v1
kind: Service
metadata:
  name: webapp

spec:
  selector:
    app: webapp
    dz: {{ .Values.label }}
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer