apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    dz: {{ .Values.label }}
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  type: LoadBalancer