apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    dz: {{ .Values.label }}

spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  type: ClusterIP