apiVersion: v1
kind: Service
metadata:
  name: grafana

spec:
  selector:
    app: grafana
    dz: {{ .Values.label }}
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer