// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: schema/Billing.proto

package BillingPB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CBResult int32

const (
	CBResult_CBResult_UNSPECIFIED    CBResult = 0
	CBResult_CBResult_Ok             CBResult = 1
	CBResult_CBResult_Enough_cash    CBResult = 2
	CBResult_CBResult_User_not_found CBResult = 3
)

// Enum value maps for CBResult.
var (
	CBResult_name = map[int32]string{
		0: "CBResult_UNSPECIFIED",
		1: "CBResult_Ok",
		2: "CBResult_Enough_cash",
		3: "CBResult_User_not_found",
	}
	CBResult_value = map[string]int32{
		"CBResult_UNSPECIFIED":    0,
		"CBResult_Ok":             1,
		"CBResult_Enough_cash":    2,
		"CBResult_User_not_found": 3,
	}
)

func (x CBResult) Enum() *CBResult {
	p := new(CBResult)
	*p = x
	return p
}

func (x CBResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CBResult) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_Billing_proto_enumTypes[0].Descriptor()
}

func (CBResult) Type() protoreflect.EnumType {
	return &file_schema_Billing_proto_enumTypes[0]
}

func (x CBResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CBResult.Descriptor instead.
func (CBResult) EnumDescriptor() ([]byte, []int) {
	return file_schema_Billing_proto_rawDescGZIP(), []int{0}
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Billing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Billing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_schema_Billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Billing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Billing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_schema_Billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DepositCashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Sum  int32  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *DepositCashRequest) Reset() {
	*x = DepositCashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Billing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositCashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositCashRequest) ProtoMessage() {}

func (x *DepositCashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Billing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositCashRequest.ProtoReflect.Descriptor instead.
func (*DepositCashRequest) Descriptor() ([]byte, []int) {
	return file_schema_Billing_proto_rawDescGZIP(), []int{2}
}

func (x *DepositCashRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DepositCashRequest) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type DepositCashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result CBResult `protobuf:"varint,1,opt,name=result,proto3,enum=Billing.CBResult" json:"result,omitempty"`
}

func (x *DepositCashResponse) Reset() {
	*x = DepositCashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Billing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositCashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositCashResponse) ProtoMessage() {}

func (x *DepositCashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Billing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositCashResponse.ProtoReflect.Descriptor instead.
func (*DepositCashResponse) Descriptor() ([]byte, []int) {
	return file_schema_Billing_proto_rawDescGZIP(), []int{3}
}

func (x *DepositCashResponse) GetResult() CBResult {
	if x != nil {
		return x.Result
	}
	return CBResult_CBResult_UNSPECIFIED
}

var File_schema_Billing_proto protoreflect.FileDescriptor

var file_schema_Billing_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22,
	0x27, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x43, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73,
	0x75, 0x6d, 0x22, 0x40, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x61, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x42, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x43, 0x42, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x2a, 0x6c, 0x0a, 0x08, 0x43, 0x42, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x18, 0x0a, 0x14, 0x43, 0x42, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x42,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x4f, 0x6b, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x43,
	0x42, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x45, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x5f, 0x63,
	0x61, 0x73, 0x68, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x42, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0x03, 0x32, 0xa0, 0x01, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x4c,
	0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x1b, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x43, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x42,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x61,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x42, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x50, 0x42, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_Billing_proto_rawDescOnce sync.Once
	file_schema_Billing_proto_rawDescData = file_schema_Billing_proto_rawDesc
)

func file_schema_Billing_proto_rawDescGZIP() []byte {
	file_schema_Billing_proto_rawDescOnce.Do(func() {
		file_schema_Billing_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_Billing_proto_rawDescData)
	})
	return file_schema_Billing_proto_rawDescData
}

var file_schema_Billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_Billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schema_Billing_proto_goTypes = []interface{}{
	(CBResult)(0),               // 0: Billing.CBResult
	(*CreateUserRequest)(nil),   // 1: Billing.CreateUserRequest
	(*CreateUserResponse)(nil),  // 2: Billing.CreateUserResponse
	(*DepositCashRequest)(nil),  // 3: Billing.DepositCashRequest
	(*DepositCashResponse)(nil), // 4: Billing.DepositCashResponse
}
var file_schema_Billing_proto_depIdxs = []int32{
	0, // 0: Billing.DepositCashResponse.result:type_name -> Billing.CBResult
	3, // 1: Billing.Billing.ChangeBalance:input_type -> Billing.DepositCashRequest
	1, // 2: Billing.Billing.CreateUser:input_type -> Billing.CreateUserRequest
	4, // 3: Billing.Billing.ChangeBalance:output_type -> Billing.DepositCashResponse
	2, // 4: Billing.Billing.CreateUser:output_type -> Billing.CreateUserResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_Billing_proto_init() }
func file_schema_Billing_proto_init() {
	if File_schema_Billing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_Billing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_Billing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_Billing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositCashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_Billing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositCashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_Billing_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_Billing_proto_goTypes,
		DependencyIndexes: file_schema_Billing_proto_depIdxs,
		EnumInfos:         file_schema_Billing_proto_enumTypes,
		MessageInfos:      file_schema_Billing_proto_msgTypes,
	}.Build()
	File_schema_Billing_proto = out.File
	file_schema_Billing_proto_rawDesc = nil
	file_schema_Billing_proto_goTypes = nil
	file_schema_Billing_proto_depIdxs = nil
}
