apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$3
  name: app-ingress
  labels:
    app: http-simple-rs
spec:
  rules:
    - host: arch.homework
      http:
        paths:
#          - path: /otusapp/(.*?)(/|$)(.*) со слешом на коце
          - path: /otusapp/(.*?)(/|$)(/|.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: http-simple-service
                port:
                  number: 2000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: http-simple-service
                port:
                  number: 2000

