apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$3
  name: app-ingress
  labels:
    app: http-simple-rs
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/(.*?)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: http-simple-service
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: http-simple-service
                port:
                  number: 80

