apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: http-simple-rs-2
  labels:
    app: http-simple-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: app-http-simple
          image: guronn/otus_service:v2
          ports:
            - containerPort: 8000
