apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: app
    dz: {{ .Values.label }}
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer