apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: auth
    dz: {{ .Values.label }}
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  type: LoadBalancer