apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
    dz: {{ .Values.label }}
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: billing
spec:
  selector:
    app: billing
    dz: {{ .Values.label }}
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  selector:
    app: notify
    dz: {{ .Values.label }}
  ports:
    - port: 8003
      protocol: TCP
      targetPort: 8003
  type: ClusterIP