// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: schema/Nats.proto

package NatsPB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositCash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Sum  int32  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *DepositCash) Reset() {
	*x = DepositCash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Nats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositCash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositCash) ProtoMessage() {}

func (x *DepositCash) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Nats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositCash.ProtoReflect.Descriptor instead.
func (*DepositCash) Descriptor() ([]byte, []int) {
	return file_schema_Nats_proto_rawDescGZIP(), []int{0}
}

func (x *DepositCash) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DepositCash) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type PayOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Sum    int32  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
	Basket string `protobuf:"bytes,3,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *PayOrder) Reset() {
	*x = PayOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Nats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrder) ProtoMessage() {}

func (x *PayOrder) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Nats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrder.ProtoReflect.Descriptor instead.
func (*PayOrder) Descriptor() ([]byte, []int) {
	return file_schema_Nats_proto_rawDescGZIP(), []int{1}
}

func (x *PayOrder) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PayOrder) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *PayOrder) GetBasket() string {
	if x != nil {
		return x.Basket
	}
	return ""
}

type Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Notify) Reset() {
	*x = Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_Nats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_schema_Nats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_schema_Nats_proto_rawDescGZIP(), []int{2}
}

func (x *Notify) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Notify) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_schema_Nats_proto protoreflect.FileDescriptor

var file_schema_Nats_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x4e, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x4e, 0x61, 0x74, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x43, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x22, 0x48,
	0x0a, 0x08, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09,
	0x5a, 0x07, 0x2f, 0x4e, 0x61, 0x74, 0x73, 0x50, 0x42, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_schema_Nats_proto_rawDescOnce sync.Once
	file_schema_Nats_proto_rawDescData = file_schema_Nats_proto_rawDesc
)

func file_schema_Nats_proto_rawDescGZIP() []byte {
	file_schema_Nats_proto_rawDescOnce.Do(func() {
		file_schema_Nats_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_Nats_proto_rawDescData)
	})
	return file_schema_Nats_proto_rawDescData
}

var file_schema_Nats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_Nats_proto_goTypes = []interface{}{
	(*DepositCash)(nil), // 0: Nats.DepositCash
	(*PayOrder)(nil),    // 1: Nats.PayOrder
	(*Notify)(nil),      // 2: Nats.Notify
}
var file_schema_Nats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_Nats_proto_init() }
func file_schema_Nats_proto_init() {
	if File_schema_Nats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_Nats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositCash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_Nats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_Nats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_Nats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_Nats_proto_goTypes,
		DependencyIndexes: file_schema_Nats_proto_depIdxs,
		MessageInfos:      file_schema_Nats_proto_msgTypes,
	}.Build()
	File_schema_Nats_proto = out.File
	file_schema_Nats_proto_rawDesc = nil
	file_schema_Nats_proto_goTypes = nil
	file_schema_Nats_proto_depIdxs = nil
}
