apiVersion: v1
kind: Secret
metadata:
  name: secretdb
  labels:
    dz: dz4
{{/*  annotations:*/}}
{{/*    "helm.sh/hook": pre-install*/}}
{{/*    "helm.sh/hook-weight": "-20"*/}}
type: kubernetes.io/basic-auth
data:
  user: "cm9vdA=="
  password : "cm9vdA=="