{
 "title": "dz5",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{ app=\"webapp\" } "
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mux_router_request_duration_seconds_count{  }[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Counter status 500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mux_router_request_duration_seconds_count{ code=\"500\"}) \r\n"
    }
   ]
  },
  {
   "title": "quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (rate (mux_router_request_duration_seconds_bucket{ }[5m]))) ",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "status 500",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(mux_router_request_duration_seconds_count{   code=\"500\"}[2m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Counter status 200",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mux_router_request_duration_seconds_count{  code=\"200\"}) \r\n"
    }
   ]
  },
  {
   "title": "percent 200",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mux_router_request_duration_seconds_count{   code=\"200\"}[30s]))/sum(increase(mux_router_request_duration_seconds_count{  }[30s]))*100\r\n"
    }
   ]
  },
  {
   "title": "quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le,route) (rate (mux_router_request_duration_seconds_bucket{ }[5m])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "status 500 by route",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (route) (increase(mux_router_request_duration_seconds_count{  code=\"500\"}[2m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "status 200 by route",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (route) (increase(mux_router_request_duration_seconds_count{   code=\"200\"}[2m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "quantile 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (rate (mux_router_request_duration_seconds_bucket{ }[5m])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{app=\"webapp\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "quantile max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le,route) (rate (mux_router_request_duration_seconds_bucket{ }[5m])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (container_label_io_kubernetes_pod_name) (container_memory_rss{container_label_io_kubernetes_container_name=\"webapp\", id=~\"/docker/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"active\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}